# SPDX-License-Identifier: Apache-2.0
# <!-- AGENT_HEADER
# role: code
# purpose: Per-directory .okuro-index.yaml sidecar metadata for files agents read but don't modify
# index:
#   imports
#   SIDECAR_FILENAME
#   SIDECAR_SCHEMA_VERSION
#   class SidecarEntry
#   def content_hash
#   def load
#   def save
#   def invalidate
#   def reconcile_directory
#   def reconcile_root
#   def entry_from_header
#   def entry_to_header
# AGENT_HEADER_END -->
"""
Per-directory .okuro-index.yaml sidecar metadata for files agents read but don't modify.

Sidecars exist because we can't inject AGENT_HEADERs into files we don't own.
Agent-created/modified files always get inline headers regardless of mode.
"""

import hashlib
import os
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import yaml

from .core import AgentHeader, FileRole, IndexEntry


SIDECAR_FILENAME = ".okuro-index.yaml"
SIDECAR_SCHEMA_VERSION = 2


@dataclass
class SidecarEntry:
    """Metadata for a single file in the sidecar index."""

    purpose: str
    role: str
    index: list[str] = field(default_factory=list)
    generated_by: str = "docstring"
    content_hash: str = ""


def content_hash(file_path: Path) -> str:
    """Compute a short content hash for invalidation."""
    try:
        data = file_path.read_bytes()
        return hashlib.md5(data).hexdigest()[:6]
    except (OSError, PermissionError):
        return ""


def load(directory: Path) -> dict[str, SidecarEntry]:
    """Read .okuro-index.yaml from a directory.

    Returns {filename: SidecarEntry} for each file listed.
    Returns empty dict if file doesn't exist or is malformed.
    """
    sidecar_path = directory / SIDECAR_FILENAME
    if not sidecar_path.exists():
        return {}

    try:
        data = yaml.safe_load(sidecar_path.read_text())
    except Exception:
        return {}

    if not data or not isinstance(data, dict) or "files" not in data:
        return {}

    entries: dict[str, SidecarEntry] = {}
    files_block = data["files"]
    if not isinstance(files_block, dict):
        return {}

    for filename, meta in files_block.items():
        if not isinstance(meta, dict):
            continue
        entries[filename] = SidecarEntry(
            purpose=meta.get("purpose", ""),
            role=meta.get("role", "code"),
            index=meta.get("index", []) or [],
            generated_by=meta.get("generated_by", "unknown"),
            content_hash=meta.get("content_hash", ""),
        )
    return entries


def _entries_to_files_data(entries: dict[str, SidecarEntry]) -> dict[str, dict]:
    files_data: dict[str, dict] = {}
    for filename, entry in sorted(entries.items()):
        file_dict: dict = {
            "purpose": entry.purpose,
            "role": entry.role,
        }
        if entry.index:
            file_dict["index"] = entry.index
        file_dict["generated_by"] = entry.generated_by
        file_dict["content_hash"] = entry.content_hash
        files_data[filename] = file_dict
    return files_data


def save(directory: Path, entries: dict[str, SidecarEntry]) -> bool:
    """Write .okuro-index.yaml atomically (tmp file + rename).

    Merges into existing file if present — caller should load() first,
    update entries, then save().

    Skips the write if the resulting `files` block would be byte-identical to
    what's already on disk (ignoring the `generated_at` timestamp). Returns
    True if the file was written, False if no write happened.
    """
    sidecar_path = directory / SIDECAR_FILENAME

    files_data = _entries_to_files_data(entries)

    # Skip no-op writes: compare to existing files block, timestamp-agnostic
    if sidecar_path.exists():
        existing_on_disk = _entries_to_files_data(load(directory))
        if existing_on_disk == files_data:
            return False

    data = {
        "version": SIDECAR_SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "generator": "okuro-cortex",
        "files": files_data,
    }

    # Atomic write: tmp file in same dir + rename
    fd, tmp_path = tempfile.mkstemp(
        dir=str(directory), suffix=".tmp", prefix=".okuro-index-"
    )
    try:
        with os.fdopen(fd, "w") as f:
            f.write(
                "# Auto-generated by okuro cortex."
                " Safe to .gitignore or commit for shared team intelligence.\n"
            )
            yaml.dump(data, f, default_flow_style=False, sort_keys=False)
        os.replace(tmp_path, str(sidecar_path))
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
    return True


def invalidate(directory: Path) -> tuple[dict[str, SidecarEntry], list[str]]:
    """Check content hashes against current files.

    Returns (valid_entries, stale_filenames).
    Stale entries are those whose content_hash no longer matches the file on disk.
    Missing files are silently dropped.
    """
    entries = load(directory)
    valid: dict[str, SidecarEntry] = {}
    stale: list[str] = []

    for filename, entry in entries.items():
        file_path = directory / filename
        if not file_path.exists():
            continue  # File deleted — drop entry
        current = content_hash(file_path)
        if current == entry.content_hash:
            valid[filename] = entry
        else:
            stale.append(filename)

    return valid, stale


def reconcile_directory(directory: Path) -> dict:
    """Drop sidecar entries for files that no longer exist on disk.

    Returns ``{"orphans_removed": N, "kept": N, "rewrote": bool}``. The
    sidecar file is rewritten only when at least one orphan was removed; if
    the directory becomes empty (no files indexed any more) the sidecar
    itself is deleted so empty stub files don't litter the tree.
    """
    sidecar_path = directory / SIDECAR_FILENAME
    if not sidecar_path.exists():
        return {"orphans_removed": 0, "kept": 0, "rewrote": False}

    entries = load(directory)
    if not entries:
        # Malformed or empty — remove the stub.
        try:
            sidecar_path.unlink()
        except OSError:
            return {"orphans_removed": 0, "kept": 0, "rewrote": False}
        return {"orphans_removed": 0, "kept": 0, "rewrote": True}

    kept: dict[str, SidecarEntry] = {}
    orphans: list[str] = []
    for filename, entry in entries.items():
        if (directory / filename).is_file():
            kept[filename] = entry
        else:
            orphans.append(filename)

    if not orphans:
        return {"orphans_removed": 0, "kept": len(kept), "rewrote": False}

    if not kept:
        try:
            sidecar_path.unlink()
        except OSError:
            pass
        return {"orphans_removed": len(orphans), "kept": 0, "rewrote": True}

    try:
        save(directory, kept)
    except OSError:
        return {"orphans_removed": 0, "kept": len(kept), "rewrote": False}
    return {"orphans_removed": len(orphans), "kept": len(kept), "rewrote": True}


def reconcile_root(root: Path) -> dict:
    """Walk every directory under ``root`` and reconcile each sidecar.

    Returns aggregate counts: ``directories``, ``orphans_removed``,
    ``kept``, ``rewrote``, ``deleted_empty``. Errors are swallowed per-dir
    so one unreadable subtree never aborts the whole reconcile.
    """
    import os

    totals = {
        "directories": 0,
        "orphans_removed": 0,
        "kept": 0,
        "rewrote": 0,
        "deleted_empty": 0,
    }
    for dirpath, _dirnames, filenames in os.walk(
        root, onerror=lambda _e: None
    ):
        if SIDECAR_FILENAME not in filenames:
            continue
        totals["directories"] += 1
        try:
            res = reconcile_directory(Path(dirpath))
        except OSError:
            continue
        totals["orphans_removed"] += res["orphans_removed"]
        totals["kept"] += res["kept"]
        if res["rewrote"]:
            if res["kept"] == 0:
                totals["deleted_empty"] += 1
            else:
                totals["rewrote"] += 1
    return totals


def entry_from_header(
    header: AgentHeader, file_hash: str, generated_by: str = "scanner"
) -> SidecarEntry:
    """Convert an AgentHeader to a SidecarEntry."""
    return SidecarEntry(
        purpose=header.purpose,
        role=header.role.value,
        index=[e.description for e in header.index],
        generated_by=generated_by,
        content_hash=file_hash,
    )


def entry_to_header(entry: SidecarEntry) -> AgentHeader:
    """Convert a SidecarEntry back to an AgentHeader for indexing."""
    try:
        role = FileRole(entry.role)
    except ValueError:
        role = FileRole.CODE

    index_entries = [
        IndexEntry(start_line=0, end_line=0, description=desc)
        for desc in entry.index
    ]

    return AgentHeader(
        role=role,
        purpose=entry.purpose,
        index=index_entries,
    )
