# SPDX-License-Identifier: Apache-2.0
"""Install-contract diagnostics — single-source-of-truth state collector.

The post-onboarding install-report.json is generated by
``okuro.diagnostics.contract.write_report``. The standalone
``scripts/contract-probe.py`` shares the same module so the wizard's
auto-report and any later manual run produce comparable JSON.
"""

from .contract import (
    ProbeResult,
    collect_state,
    write_report,
    LATEST_REPORT_PATH,
)

__all__ = [
    "ProbeResult",
    "collect_state",
    "write_report",
    "LATEST_REPORT_PATH",
]
