/**
 * Hands a slide-generation request from the (global) chat "slides" action to the
 * SlidesPage that mounts after navigation — mirrors flow-stream's queue. The
 * page consumes the pending topic on mount and runs generation.
 *
 * THE OLD PREDICATE WAS WRONG UNDER THE SHELL, and invisibly so — the same
 * class as `lib/flow-stream.ts`'s, fixed in the p4 WORK pass. Two call sites in
 * `components/shell/chat-capabilities.tsx` tested
 * `window.location.pathname.startsWith("/slides")`, and the shell mounts this
 * leaf at `/deliver/slides`. So the test was FALSE on the very leaf it was
 * asking about: the `else` branch ran `navigate("/slides")`, which redirects to
 * `/deliver/slides` — the address the user is already on — so no remount
 * happened, and `takeSlideGen()` is drained only in a mount effect. Asking the
 * chat to build a deck WHILE ON SLIDES queued the request and nothing consumed
 * it. Worse, the queue was left full, so the stale topic generated by surprise
 * the next time the leaf really did mount.
 *
 * Centralised here so every caller shares the one correct predicate, exactly as
 * `flow-stream.ts` does. The listener lives in the leaf component, which stays
 * mounted across the gallery, the editor and the reader, so "on the leaf" is
 * the whole condition — there is no document requirement, because generating IS
 * how a deck comes into existence.
 */
export const SLIDES_LEAF = "/deliver/slides";

/** Is a SlidesPage mounted right now, i.e. will a dispatched event be heard? */
export function onSlidesLeaf(pathname = window.location.pathname): boolean {
  return pathname === SLIDES_LEAF || pathname.startsWith(SLIDES_LEAF + "/");
}

export type GenMode = "fast" | "quality";
interface PendingGen { topic: string; personId?: string; mode?: GenMode; brandId?: string }
let _pending: PendingGen | null = null;

export function queueSlideGen(topic: string, personId?: string, mode?: GenMode, brandId?: string): void {
  _pending = { topic, personId, mode, brandId };
}

export function takeSlideGen(): PendingGen | null {
  const p = _pending;
  _pending = null;
  return p;
}

// The deck currently open in the SlidesPage — so the global chat's "slides_edit"
// action knows which deck to edit/review without threading it through routing.
let _openDeckId: string | null = null;
export function setOpenDeckId(id: string | null): void {
  _openDeckId = id;
}
export function getOpenDeckId(): string | null {
  return _openDeckId;
}
