# SPDX-License-Identifier: Apache-2.0
# <!-- AGENT_HEADER
# role: code
# purpose: Provenance record for okuro-written instruction files — the hand-edit warning's non-agent channel.
# index:
#   MANIFEST_FILENAME
#   MANIFEST_SCHEMA_VERSION
#   CLOBBER_REPORT_DAYS
#   MAINTAINER_NOTICE
#   def manifest_path
#   def manifest_state
#   def load
#   def entry
#   def record
#   def write_managed
#   def status
# AGENT_HEADER_END -->
"""Provenance record for the instruction files okuro writes into agent homes.

WHY THIS EXISTS. Until 2026-09-09 every generated instruction file opened
with ``# Auto-generated by okuro. Do not edit manually.`` That sentence is
addressed to a MAINTAINER, and it sat at the top of the document that claims
to be the AGENT's highest-priority instructions — so it was misdelivered by
construction. It was removed, and ``tests/providers/test_golden.py`` now
fails if it comes back. The warning still has a real job, so it needs a
channel that is not an agent's context. This module is that channel.

WHAT IT REPLACES THE BANNER WITH. A banner only ever proved a file *started*
as okuro's — copy it into a hand-written CLAUDE.md and the check passes. A
content hash proves the file *still is* okuro's. ``okuro doctor`` reads it
(``_check_instructions_deployed``); no agent ever does, because it lives
under ``~/.okuro`` and no CLI loads it.

WHY THE RECORD IS STICKY. A live hash comparison alone would almost never
fire. The daemon's ``refresh`` task (registry.py, cron ``*/5``) regenerates
all of these files every five minutes, so a hand edit is overwritten with
byte-identical canonical content and the hash matches again — the evidence is
destroyed before anyone runs the doctor. So the detection happens at the
moment of the OVERWRITE, not at the moment of the check: ``write_managed``
compares what is on disk against what it is about to write, and stamps
``clobbered_at`` on the entry when it is about to discard someone's edit.
The doctor reports that stamp for ``CLOBBER_REPORT_DAYS``, which is how the
user finds out where their edit went.

SCOPE — WHOLE-FILE OWNERSHIP ONLY. Record a path here only when okuro owns
every byte of it. ``~/.gemini/GEMINI.md`` and ``~/.codex/config.toml`` carry
an okuro-managed BLOCK inside a user-owned file; a whole-file digest would
report "modified" the moment the user edits their own half, which is exactly
the false alarm this record exists to avoid.
"""

from __future__ import annotations

import json
import logging
import os
from hashlib import sha256
from pathlib import Path

from okuro.clock import age_seconds, utc_iso
from okuro.db.engine import okuro_home

from ._profile_compliance import atomic_write_json, atomic_write_text

log = logging.getLogger(__name__)

MANIFEST_FILENAME = "deployed-instructions.json"
MANIFEST_SCHEMA_VERSION = 1

# How long a discarded hand edit stays worth reporting. Long enough that the
# user reaches the doctor after noticing their change vanished; short enough
# that the warning clears itself without a state machine or an ack command.
CLOBBER_REPORT_DAYS = 7

# The hand-edit warning itself. It ships in the manifest — a file only a
# maintainer opens — instead of in the files an agent loads.
MAINTAINER_NOTICE = (
    "okuro generates the files listed here from your profile and overwrites "
    "them: the daemon's refresh task rewrites them every 5 minutes and every "
    "profile save regenerates them. A hand edit does not survive. Change your "
    "profile instead (okuro settings), or put your own rules in a file okuro "
    "does not manage — a per-project CLAUDE.md, or ~/.codex/AGENTS.override.md. "
    "`okuro doctor` reports any file below whose content no longer matches the "
    "hash recorded here, and any change okuro destroyed in the last "
    f"{CLOBBER_REPORT_DAYS} days. What it destroyed is not lost: the discarded "
    "bytes are kept under ~/.okuro/archive/instructions/, and the entry's "
    "clobbered_copy field names the file."
)


def manifest_path() -> Path:
    """Absolute path of the provenance manifest under ``$OKURO_HOME``."""
    return okuro_home() / MANIFEST_FILENAME


def manifest_state() -> str:
    """``ok`` | ``missing`` | ``unreadable``.

    The doctor needs these apart. A MISSING manifest is the fresh-install
    case and ``okuro init`` fixes it. An UNREADABLE one means okuro deployed
    the files correctly and cannot prove it — reporting that as "not
    deployed" would repeat, with a new cause, the exact defect this module
    was written to end: a correctly deployed file called undeployed.
    """
    path = manifest_path()
    if not path.is_file():
        return "missing"
    try:
        json.loads(path.read_text())
    except (OSError, ValueError):
        return "unreadable"
    return "ok"


def _digest_bytes(data: bytes) -> str:
    return sha256(data).hexdigest()


def _digest(path: str | Path) -> str:
    """SHA-256 of the file's bytes ON DISK.

    Hashing what is on disk rather than the string we meant to write keeps
    the record honest on Windows, where text-mode ``open`` translates
    ``\\n`` to ``\\r\\n`` and the on-disk bytes differ from the content.
    """
    return _digest_bytes(Path(path).read_bytes())


def _same_text(disk: bytes, content: str) -> bool:
    """True when disk holds this content, ignoring line-ending translation.

    Used to tell a REGENERATION apart from a HAND EDIT. Two okuro writers can
    race (the ``*/5`` daemon refresh against a profile save), and both write
    the same canonical text; that is not an edit and must never be stamped as
    one.
    """
    try:
        decoded = disk.decode()
    except UnicodeDecodeError:
        return False
    return decoded.replace("\r\n", "\n") == content.replace("\r\n", "\n")


def load() -> dict[str, dict]:
    """Return ``{absolute_path: entry}``. Missing or corrupt manifest → ``{}``."""
    try:
        data = json.loads(manifest_path().read_text())
    except (OSError, ValueError):
        return {}
    files = data.get("files") if isinstance(data, dict) else None
    return files if isinstance(files, dict) else {}


def entry(path: str | Path, files: dict[str, dict] | None = None) -> dict:
    """The manifest entry for ``path``, or ``{}``."""
    entries = load() if files is None else files
    found = entries.get(str(Path(path).expanduser()))
    return found if isinstance(found, dict) else {}


def clobbered_recently(record_entry: dict) -> dict | None:
    """A destroyed user change still worth reporting: ``{at, kind, copy}``.

    None once it is older than :data:`CLOBBER_REPORT_DAYS` — which is how the
    warning clears itself, without an ack command or a state machine.
    """
    stamp = record_entry.get("clobbered_at")
    if not isinstance(stamp, str) or not stamp:
        return None
    try:
        if age_seconds(stamp) > CLOBBER_REPORT_DAYS * 86400:
            return None
    except Exception:  # noqa: BLE001 — an unparsable stamp is still evidence
        pass
    return {
        "at": stamp,
        "kind": record_entry.get("clobbered_kind") or "edited",
        "copy": record_entry.get("clobbered_copy"),
    }


def record(
    path: str | Path,
    provider: str,
    clobbered_sha256: str | None = None,
    clobbered_kind: str | None = None,
    clobbered_copy: str | None = None,
) -> bool:
    """Record the on-disk digest of ``path`` as okuro-written.

    The ``clobbered_*`` arguments describe a user change this write destroyed
    — its digest, whether it was an edit / an emptied file / a deletion, and
    where the discarded bytes were archived. Set them only for content that
    did not come from okuro (see :func:`write_managed`). They stick to the
    entry across later regenerations, because the regenerated file hashes
    identically to the one the edit replaced and a live comparison can no
    longer see that anything happened.

    Returns True when the manifest holds a current entry afterwards. A no-op
    (still True) when nothing changed — the daemon regenerates identical
    content every 5 minutes and there is no reason to rewrite the manifest
    288 times a day.
    """
    target = str(Path(path).expanduser())
    try:
        digest = _digest(target)
        size = os.path.getsize(target)
    except OSError as exc:
        log.warning("deployment record: cannot hash %s: %s", target, exc)
        return False

    try:
        raw = json.loads(manifest_path().read_text())
        if not isinstance(raw, dict):
            raw = {}
    except (OSError, ValueError):
        raw = {}
    files = raw.get("files")
    if not isinstance(files, dict):
        files = {}

    previous = files.get(target) if isinstance(files.get(target), dict) else {}
    notice_current = (
        raw.get("_notice") == MAINTAINER_NOTICE
        and raw.get("schema") == MANIFEST_SCHEMA_VERSION
    )
    if (
        previous.get("sha256") == digest
        and clobbered_kind is None
        and notice_current
    ):
        # Nothing new to say — and the notice/schema on disk are current, so
        # a reworded notice or a schema bump still reaches the file.
        return True

    updated = dict(previous)
    updated.update(
        {
            "sha256": digest,
            "bytes": size,
            "provider": provider,
            "written_at": utc_iso(),
        }
    )
    if clobbered_kind:
        # A new clobber REPLACES the old one wholesale. Merging would leave the
        # previous event's archive path attached to this one — the doctor would
        # then point the user at bytes that are not the ones just destroyed.
        for stale in ("clobbered_sha256", "clobbered_copy"):
            updated.pop(stale, None)
        updated["clobbered_at"] = utc_iso()
        updated["clobbered_kind"] = clobbered_kind
        if clobbered_sha256:
            updated["clobbered_sha256"] = clobbered_sha256
        if clobbered_copy:
            updated["clobbered_copy"] = clobbered_copy
    files[target] = updated

    payload = {
        "_notice": MAINTAINER_NOTICE,
        "schema": MANIFEST_SCHEMA_VERSION,
        "files": files,
    }
    try:
        atomic_write_json(str(manifest_path()), payload)
    except OSError as exc:
        log.warning("deployment record: cannot write manifest: %s", exc)
        return False

    # THIS BRANCH IS THE CHANGE SIGNAL. Reaching it means the digest differs
    # from what was recorded (the equal-digest case returned above), so it is
    # the exact moment a new instruction version became live — the only moment
    # anything can observe it, because the manifest overwrites the old entry
    # and five minutes later the file is byte-identical again.
    #
    # The ledger is what makes a past session attributable; the manifest alone
    # can only ever answer "what is live now". A failure here is logged inside
    # note_version and costs one unattributable interval, never a failed
    # instruction deploy.
    if previous.get("sha256") != digest:
        from ._instruction_ledger import note_version

        note_version(target, provider, digest, size, at=updated["written_at"])
    return True


def _archive_discarded(target: str, provider: str, data: bytes) -> str | None:
    """Keep the bytes this write is about to destroy. Returns the copy's path.

    A digest proves an edit existed; it cannot give it back. okuro already
    archives rather than deletes in the same situation elsewhere — the claude
    adapter moves superseded project-memory files into
    ``~/.okuro/archive/claude-memory/``, the codex adapter archives the legacy
    ``instructions.md`` — so this is that convention, not a new one.
    """
    try:
        archive_dir = okuro_home() / "archive" / "instructions" / provider
        archive_dir.mkdir(parents=True, exist_ok=True)
        stamp = utc_iso().replace(":", "").replace("-", "")
        copy = archive_dir / f"{Path(target).name}.{stamp}"
        copy.write_bytes(data)
        return str(copy)
    except OSError as exc:
        log.warning("deployment record: cannot archive %s: %s", target, exc)
        return None


def write_managed(path: str | Path, content: str, provider: str) -> str:
    """Write an okuro-owned instruction file and record its provenance.

    The single seam every provider adapter uses, so a new adapter cannot ship
    an instruction file the doctor then reports as unmanaged. Also the only
    moment at which a user's change is observable: whatever is on disk here is
    about to be destroyed, so if it is not okuro's it is archived and recorded
    first. Three shapes of "the user said no" reach this point — an edit, an
    emptied file, and a deletion — and all three are otherwise undone within
    five minutes with nothing left to show it happened.

    A failed record is logged, never raised: the file on disk is the
    deliverable and a missing record costs one doctor warning, not a broken
    install.
    """
    target = str(Path(path).expanduser())

    discarded: str | None = None
    archived: str | None = None
    kind: str | None = None
    state = status(target)
    if state == "modified":
        try:
            on_disk: bytes | None = Path(target).read_bytes()
        except OSError:
            on_disk = None  # NOT b"" — an emptied file is a real edit, and the
            # falsy-sentinel version of this let `: > CLAUDE.md` pass silently.
        # Byte-identical (modulo line endings) means another okuro writer got
        # there first — a race, not an edit.
        if on_disk is not None and not _same_text(on_disk, content):
            discarded = _digest_bytes(on_disk)
            kind = "emptied" if on_disk == b"" else "edited"
            if on_disk:
                archived = _archive_discarded(target, provider, on_disk)
    elif state == "missing" and entry(target).get("sha256"):
        # okuro wrote this file, the user deleted it, and this write is about
        # to put it back. The most explicit refusal there is, and the one the
        # live hash comparison can least afford to forget.
        discarded = ""
        kind = "deleted"

    atomic_write_text(target, content)
    record(
        target,
        provider,
        clobbered_sha256=discarded,
        clobbered_kind=kind,
        clobbered_copy=archived,
    )
    return target


def status(path: str | Path, files: dict[str, dict] | None = None) -> str:
    """Provenance state of ``path``.

    ``managed``    — exists, recorded, digest matches: okuro wrote it and it
                     has not been touched since.
    ``modified``   — exists and recorded, digest differs: hand-edited (or
                     written by something other than okuro) since the record.
    ``unmanaged``  — exists but okuro has no record of writing it.
    ``missing``    — no such file.
    ``unreadable`` — exists but cannot be read.

    Pass ``files`` (from :func:`load`) to check several paths against one
    manifest read.
    """
    target = Path(path).expanduser()
    if not target.is_file():
        return "missing"
    recorded = entry(target, files).get("sha256")
    if not recorded:
        return "unmanaged"
    try:
        return "managed" if _digest(target) == recorded else "modified"
    except OSError:
        return "unreadable"


__all__ = [
    "CLOBBER_REPORT_DAYS",
    "MAINTAINER_NOTICE",
    "MANIFEST_FILENAME",
    "MANIFEST_SCHEMA_VERSION",
    "clobbered_recently",
    "entry",
    "load",
    "manifest_path",
    "manifest_state",
    "record",
    "status",
    "write_managed",
]
