# SPDX-License-Identifier: Apache-2.0
# <!-- AGENT_HEADER
# role: code
# purpose: Antigravity provider adapter.
# index: imports | hook script | class AntigravityAdapter
# AGENT_HEADER_END -->
"""Antigravity provider adapter.

System-tier communication delivery
----------------------------------
Antigravity (Gemini-family CLI/IDE) has two channels above the AGENTS.md tier
that okuro uses to deliver the profile-driven communication directive:

  * An **Always-On rule** in ``~/.gemini/GEMINI.md`` — appended to the system
    instructions and overriding lower tiers. Written as a clearly-marked okuro
    managed block so it merges with (never clobbers) any user content, and so
    it does not collide destructively with the Gemini CLI's own use of
    ``GEMINI.md``. Body is the SAME ``build_comm_directive`` used by the Claude
    output style and the Codex ``developer_instructions`` — one source, no
    drift.
  * A ``PreInvocation`` **command** hook (``~/.gemini/config/hooks.json``) that
    injects the per-turn context as an ephemeral system message via
    ``injectSteps``. Reads the SAME ``~/.okuro/profile-turn-context.txt`` the
    Claude and Codex hooks read.

Antigravity only runs ``type: "command"`` hook handlers. Its config paths
churn across versions, so the hook installer verifies the target dir and logs
(rather than failing) when it is absent.
"""

import json
import logging
import os
import shutil
from pathlib import Path

from . import register
from .base import ProviderAdapter

log = logging.getLogger(__name__)


# Managed-block markers for the Always-On rule inside ~/.gemini/GEMINI.md.
# Everything between them is okuro-owned and rewritten each regen; everything
# outside is preserved verbatim.
_GEMINI_BLOCK_BEGIN = "<!-- OKURO:COMM-PROTOCOL:BEGIN — auto-generated, do not edit -->"
_GEMINI_BLOCK_END = "<!-- OKURO:COMM-PROTOCOL:END -->"


# PreInvocation command hook. Self-contained (Antigravity may launch it under a
# bare system python), reads the shared per-turn context cache, and emits the
# Antigravity PreInvocation contract: injectSteps -> ephemeralMessage (a
# transient system message injected before the model runs).
PREINVOCATION_HOOK = r"""#!/usr/bin/env python3
# Antigravity PreInvocation hook: inject okuro per-turn profile context.
# Auto-generated by okuro. Do not edit manually.
import sys, json, os

CONTEXT_PATH = os.path.expanduser("~/.okuro/profile-turn-context.txt")


def _emit(payload):
    print(json.dumps(payload))
    sys.exit(0)


if not os.path.isfile(CONTEXT_PATH):
    _emit({})

try:
    with open(CONTEXT_PATH) as _f:
        context = _f.read().strip()
except Exception:
    _emit({})

if not context:
    _emit({})

try:
    json.load(sys.stdin)
except Exception:
    pass

_emit({"injectSteps": [{"ephemeralMessage": context}]})
"""


@register
class AntigravityAdapter(ProviderAdapter):
    name = "antigravity"

    _HOOK_NAME = "okuro-comm-protocol"
    _HOOK_FILENAME = "okuro-preinvocation.py"

    def detect(self) -> bool:
        return (
            shutil.which("antigravity") is not None
            or os.path.isdir(os.path.expanduser("~/.config/Antigravity"))
            or os.path.isdir(os.path.expanduser("~/.antigravity"))
            or Path("/Applications/Antigravity.app").is_dir()
        )

    def generate_instructions(self) -> list[str]:
        from ..bootstrap.sections import build_behavioral_section
        from .template import build_instructions

        generated: list[str] = []
        gemini_dir = os.path.expanduser("~/.gemini")
        os.makedirs(gemini_dir, exist_ok=True)

        behavioral = build_behavioral_section()
        target = os.path.join(gemini_dir, "AGENTS.md")
        try:
            with open(target, "w") as f:
                f.write(build_instructions("antigravity", behavioral))
            generated.append(target)
        except (IOError, OSError):
            pass

        # System-tier: Always-On rule in GEMINI.md. Lives in
        # generate_instructions() so the settings-edit regen path keeps it
        # synced with the live profile.
        generated.extend(self._write_gemini_always_on(gemini_dir))

        return generated

    # -----------------------------------------------------------------
    # System-tier — Always-On rule in GEMINI.md (managed block)
    # -----------------------------------------------------------------

    def _write_gemini_always_on(self, gemini_dir: str) -> list[str]:
        """Insert/refresh the okuro comm-directive managed block in GEMINI.md.

        Merge-safe: only the region between the BEGIN/END markers is owned by
        okuro. Any user content before/after is preserved verbatim. Idempotent:
        a no-op when the block already holds the current directive. Skips
        entirely when there is no profile (no directive to write).
        """
        from ._profile_compliance import atomic_write_text, build_comm_directive

        directive = build_comm_directive()
        if not directive or not directive.strip():
            return []

        block = (
            _GEMINI_BLOCK_BEGIN
            + "\n\n## Communication protocol (okuro — Always-On)\n\n"
            + directive.strip()
            + "\n\n"
            + _GEMINI_BLOCK_END
        )

        gemini_md = os.path.join(gemini_dir, "GEMINI.md")
        existing = ""
        if os.path.isfile(gemini_md):
            try:
                with open(gemini_md) as f:
                    existing = f.read()
            except OSError as e:
                log.warning("antigravity: GEMINI.md unreadable (%s); skipping", e)
                return []

        begin = existing.find(_GEMINI_BLOCK_BEGIN)
        end = existing.find(_GEMINI_BLOCK_END)
        if begin != -1 and end != -1 and end > begin:
            end_full = end + len(_GEMINI_BLOCK_END)
            new_text = existing[:begin] + block + existing[end_full:]
        elif existing.strip():
            new_text = existing.rstrip() + "\n\n" + block + "\n"
        else:
            new_text = block + "\n"

        if new_text == existing:
            return []

        try:
            atomic_write_text(gemini_md, new_text)
        except OSError as e:
            log.warning("antigravity: GEMINI.md write failed: %s", e)
            return []
        return [gemini_md]

    # -----------------------------------------------------------------
    # Per-turn — PreInvocation command hook
    # -----------------------------------------------------------------

    def enforcement_capability(self) -> dict:
        return {
            "provider": self.name,
            "blocking_pre_tool": True,
            "shell_tool": "run_command",
            "command_field": "toolCall.args.CommandLine",
            "deny_contract": 'stdout {"decision": "deny", "reason": ...}',
            # Read out of the INSTALLED build's own hook documentation
            # (~/.gemini/antigravity-cli/builtin/skills/agy-customizations/
            # docs/hooks.md), not from a web search. That file also pins the
            # matcher shape: PreToolUse handlers are wrapped in a group with a
            # regex matcher, and tool names are the lowercased step type with
            # the CORTEX_STEP_TYPE_ prefix removed.
            "verified": "2026-07-27 — contract read from the installed "
                        "antigravity-cli build's hooks.md",
            "degradation": (
                "capability confirmed but no okuro gate is emitted for "
                "Antigravity yet — enforcement here is instructions-only "
                "until an emitter ships"
            ),
        }

    def install_hooks(self) -> list[str]:
        """Install the PreInvocation command hook + refresh its payload cache.

        The global customization root for Antigravity is ``~/.gemini/config/``
        (``hooks.json`` lives there). Paths churn across builds, so we verify
        ``~/.gemini`` exists and LOG rather than fail if the tree is absent.
        """
        generated: list[str] = []
        gemini_dir = os.path.expanduser("~/.gemini")
        if not os.path.isdir(gemini_dir):
            log.warning(
                "antigravity: ~/.gemini absent; skipping PreInvocation hook "
                "install (build layout may differ on this machine)"
            )
            return generated

        from ._profile_compliance import (
            atomic_write_json,
            atomic_write_text,
            write_profile_turn_context,
        )

        # 1. Hook script under ~/.gemini/hooks/.
        hooks_dir = os.path.join(gemini_dir, "hooks")
        try:
            os.makedirs(hooks_dir, exist_ok=True)
            hook_path = os.path.join(hooks_dir, self._HOOK_FILENAME)
            atomic_write_text(hook_path, PREINVOCATION_HOOK)
            os.chmod(hook_path, 0o755)
            generated.append(hook_path)
        except OSError as e:
            log.warning("antigravity: hook script write failed: %s", e)
            return generated

        # 2. Register in ~/.gemini/config/hooks.json (merge-safe, named-key).
        config_dir = os.path.join(gemini_dir, "config")
        try:
            os.makedirs(config_dir, exist_ok=True)
            hooks_json_path = os.path.join(config_dir, "hooks.json")
            merged = self._merge_hooks_json(hooks_json_path, hook_path)
            atomic_write_json(hooks_json_path, merged)
            generated.append(hooks_json_path)
        except Exception as e:  # noqa: BLE001
            log.warning("antigravity: hooks.json merge failed: %s", e)

        # 3. Refresh the shared per-turn payload cache.
        try:
            generated.append(write_profile_turn_context())
        except Exception as e:  # noqa: BLE001
            log.warning("antigravity: profile-turn-context.txt refresh failed: %s", e)

        log.info("antigravity: installed PreInvocation hook %s", hook_path)
        return generated

    def _merge_hooks_json(self, hooks_json_path: str, hook_path: str) -> dict:
        """Return hooks.json with okuro's named PreInvocation hook merged in.

        Antigravity's hooks.json is keyed by hook NAME at the top level. We own
        exactly the ``okuro-comm-protocol`` key and preserve every other named
        hook verbatim.
        """
        data: dict = {}
        if os.path.isfile(hooks_json_path):
            try:
                with open(hooks_json_path) as f:
                    loaded = json.load(f)
                if isinstance(loaded, dict):
                    data = loaded
            except (OSError, json.JSONDecodeError) as e:
                log.warning(
                    "antigravity: hooks.json unreadable/corrupt (%s); rewriting fresh", e
                )
                data = {}

        # PreInvocation is a FLAT list of handler objects (no matcher wrapper).
        data[self._HOOK_NAME] = {
            "PreInvocation": [
                {
                    "type": "command",
                    "command": f'python3 "{hook_path}"',
                    "timeout": 10,
                }
            ]
        }
        return data

    def get_subagent_protocol(self, bootstrap_context: str) -> str:
        from .template import build_subagent_protocol
        return build_subagent_protocol()
