# SPDX-License-Identifier: Apache-2.0
# <!-- AGENT_HEADER
# role: code
# purpose: Codex provider adapter.
# index: imports | hook script | class CodexAdapter
# AGENT_HEADER_END -->
"""Codex provider adapter.

System-tier communication delivery
----------------------------------
Codex exposes two channels above the AGENTS.md instruction tier that okuro
uses to land the profile-driven communication directive with real weight:

  * ``developer_instructions`` in ``~/.codex/config.toml`` — developer-tier
    system text, above AGENTS.md. Written from the SAME
    ``build_comm_directive`` used by the Claude output style, so the two
    providers can never drift.
  * A ``UserPromptSubmit`` **command** hook (config in ``~/.codex/hooks.json``)
    that injects the per-turn context via ``additionalContext``. The hook
    reads the SAME ``~/.okuro/profile-turn-context.txt`` the Claude hook
    reads — one payload source across providers.

Codex only runs ``type = "command"`` hook handlers (``prompt``/``agent``
handlers are parsed but skipped), and every non-managed command hook must be
trusted once via the ``/hooks`` CLI command before it fires.
"""

import json
import logging
import os
import re
import shutil

from . import register
from .base import ProviderAdapter
from okuro.db.engine import okuro_home

log = logging.getLogger(__name__)


# Instruction body now lives in providers/template.py — see build_instructions().


# UserPromptSubmit command hook. Self-contained (Codex may launch it under a
# bare system python), reads the shared per-turn context cache, and emits the
# Codex hook contract: hookSpecificOutput.additionalContext. Byte-for-byte the
# same contract Claude Code's UserPromptSubmit hook uses — the single payload
# source is ~/.okuro/profile-turn-context.txt, written by okuro from the live
# profile.
USER_PROMPT_HOOK = r"""#!/usr/bin/env python3
# Codex UserPromptSubmit hook: inject okuro per-turn profile context.
# Auto-generated by okuro. Do not edit manually.
import sys, json, os

CONTEXT_PATH = os.path.expanduser("~/.okuro/profile-turn-context.txt")


def _exit_clean():
    sys.exit(0)


if not os.path.isfile(CONTEXT_PATH):
    _exit_clean()

try:
    with open(CONTEXT_PATH) as _f:
        context = _f.read().strip()
except Exception:
    _exit_clean()

if not context:
    _exit_clean()

try:
    json.load(sys.stdin)
except Exception:
    pass

print(json.dumps({
    "hookSpecificOutput": {
        "hookEventName": "UserPromptSubmit",
        "additionalContext": context,
    }
}))
sys.exit(0)
"""


@register
class CodexAdapter(ProviderAdapter):
    name = "codex"

    _HOOK_FILENAME = "okuro-user-prompt.py"

    def detect(self) -> bool:
        return (
            shutil.which("codex") is not None
            or os.path.isdir(os.path.expanduser("~/.codex"))
        )

    def generate_instructions(self) -> list[str]:
        from ..bootstrap.sections import build_behavioral_section
        from .template import build_instructions
        generated = []

        # User-level ~/.codex/AGENTS.md — Codex CLI 0.x loads only AGENTS.md
        # (plus the AGENTS.override.md sibling) as global instructions. The
        # historical `instructions.md` is no longer read by the runtime and
        # writing it produces a dead file. Spec:
        # https://developers.openai.com/codex/guides/agents-md
        codex_dir = os.path.expanduser("~/.codex")
        os.makedirs(codex_dir, exist_ok=True)

        # Codex has no `read` directives — content must be self-contained.
        behavioral = build_behavioral_section()
        codex_instructions = os.path.join(codex_dir, "AGENTS.md")
        try:
            with open(codex_instructions, "w") as f:
                f.write(build_instructions("codex", behavioral))
            generated.append(codex_instructions)
        except (IOError, OSError):
            pass

        # System-tier: developer_instructions in config.toml. Lives in
        # generate_instructions() (not install_hooks) so the settings-edit
        # regen path — regen_all_provider_instructions, which calls only
        # generate_instructions — keeps it synced with the live profile.
        generated.extend(self._write_comm_developer_instructions(codex_dir))

        # One-shot migration: archive the legacy instructions.md so probes,
        # uninstall, and the user don't see a stale file masquerading as
        # current truth. Only runs when the legacy file still sits on disk.
        legacy = os.path.join(codex_dir, "instructions.md")
        if os.path.isfile(legacy):
            try:
                from pathlib import Path
                import shutil as _shutil
                import time as _time
                archive_dir = okuro_home() / "archive" / "codex-instructions"
                archive_dir.mkdir(parents=True, exist_ok=True)
                ts = _time.strftime("%Y%m%dT%H%M%S")
                _shutil.move(legacy, str(archive_dir / f"instructions.{ts}.md"))
                log.info("archived legacy %s — Codex CLI no longer reads this path", legacy)
            except Exception as e:
                log.warning("legacy instructions.md archive failed: %s", e)

        return generated

    # -----------------------------------------------------------------
    # System-tier — developer_instructions in config.toml
    # -----------------------------------------------------------------

    def _write_comm_developer_instructions(self, codex_dir: str) -> list[str]:
        """Merge the comm directive into ``config.toml`` ``developer_instructions``.

        Merge-safe by construction: the existing file is preserved byte-for-byte
        except for the single top-level ``developer_instructions`` key, which is
        a scalar written at the top of the document (valid TOML — root keys bind
        before any ``[table]``). The candidate result is re-parsed with tomllib
        before it is written, so a malformed splice can never overwrite a valid
        config. Idempotent: a no-op when the key already holds the directive.

        Never writes a blank value — Codex validates ``developer_instructions``
        as non-blank and errors on an empty string. If there is no profile,
        we leave the key untouched.
        """
        from ._profile_compliance import atomic_write_text, build_comm_directive

        directive = build_comm_directive()
        if not directive or not directive.strip():
            return []

        try:
            import tomllib  # py311+
        except ModuleNotFoundError:  # pragma: no cover
            log.warning("codex: tomllib unavailable; skipping developer_instructions")
            return []
        try:
            import toml  # writer (comment-free round-trip of the KV line only)
        except ModuleNotFoundError:  # pragma: no cover
            log.warning("codex: toml writer unavailable; skipping developer_instructions")
            return []

        config_path = os.path.join(codex_dir, "config.toml")
        existing_text = ""
        if os.path.isfile(config_path):
            try:
                with open(config_path) as f:
                    existing_text = f.read()
            except OSError as e:
                log.warning("codex: config.toml unreadable (%s); skipping", e)
                return []
            # Validate current file parses before we touch it — refuse to
            # rewrite a config we cannot understand.
            try:
                tomllib.loads(existing_text)
            except Exception as e:
                log.warning("codex: config.toml unparseable (%s); skipping", e)
                return []

        # Render the single KV line via the toml encoder so quoting/escaping
        # of the multi-line directive is correct.
        kv_line = toml.dumps({"developer_instructions": directive}).strip()

        # Idempotency: already the first line? nothing to do.
        if existing_text.startswith(kv_line + "\n") or existing_text.strip() == kv_line:
            return []

        # Drop any prior top-level developer_instructions line (single-line
        # escaped string as emitted by the toml encoder), then re-prepend.
        stripped = re.sub(
            r'(?m)^developer_instructions\s*=\s*"(?:[^"\\]|\\.)*"[ \t]*\r?\n?',
            "",
            existing_text,
        )
        new_text = kv_line + "\n" + stripped

        # Safety gate: the spliced document must parse, and the key must hold
        # exactly the directive we intended.
        try:
            parsed = tomllib.loads(new_text)
        except Exception as e:
            log.warning("codex: developer_instructions splice failed to parse (%s); skipping", e)
            return []
        if parsed.get("developer_instructions") != directive:
            log.warning("codex: developer_instructions splice mismatch; skipping")
            return []

        try:
            atomic_write_text(config_path, new_text)
        except OSError as e:
            log.warning("codex: config.toml write failed: %s", e)
            return []
        return [config_path]

    # -----------------------------------------------------------------
    # Per-turn — UserPromptSubmit command hook
    # -----------------------------------------------------------------

    def enforcement_capability(self) -> dict:
        return {
            "provider": self.name,
            "blocking_pre_tool": True,
            # INPUT shape pinned by observing a REAL payload, not by reading
            # docs: an isolated CODEX_HOME with a dumping PreToolUse hook,
            # one `codex exec` turn, captured verbatim:
            #   {"session_id":..., "turn_id":..., "transcript_path":...,
            #    "cwd":"/tmp", "hook_event_name":"PreToolUse",
            #    "model":"gpt-5.5", "permission_mode":"bypassPermissions",
            #    "tool_name":"Bash", "tool_input":{"command":"echo okuro-probe"},
            #    "tool_use_id":"call_..."}
            # It is IDENTICAL to Claude Code's PreToolUse input, down to the
            # field names — which no documentation or web source stated.
            "shell_tool": "Bash",
            "command_field": "tool_input.command",
            # COVERAGE, corrected 2026-07-29. The record said "Bash only".
            # openai/codex#20204 (OPEN, updated 2026-06-14) measures which
            # handlers actually implement pre_tool_use_payload: shell,
            # unified_exec, apply_patch and mcp. Every other handler returns
            # the trait default None. So it is 4 handlers — not 1, and not the
            # "all local function tools" the vendor doc claims. apply_patch
            # and mcp are gateable on Codex today and okuro is not using them.
            "tool_coverage": ("shell", "unified_exec", "apply_patch", "mcp"),
            # STILL UNPINNED, deliberately. Returning {"decision":"allow"} made
            # Codex log `hook: PreToolUse Failed`, so that shape is wrong. The
            # binary embeds `permissionDecision` and `hookSpecificOutput`,
            # which is Claude Code's PreToolUse OUTPUT shape, so it very
            # probably mirrors that too — but "very probably" is what a guessed
            # gate is made of, and a wrong deny shape yields a hook that runs,
            # logs nothing useful, and never blocks. Two attempts to confirm it
            # timed out without capturing. Left None until observed.
            "deny_contract": None,
            "verified": "2026-07-27 — input shape captured from a live "
                        "PreToolUse payload (isolated CODEX_HOME); deny shape "
                        "attempted twice and NOT captured. 2026-07-29 — hook "
                        "coverage corrected to 4 handlers per openai/codex"
                        "#20204 (OPEN); hooks are now enabled by default "
                        "([features] hooks = false disables), and "
                        "allow_managed_hooks_only in requirements.toml lets an "
                        "enterprise deployment ignore okuro's hooks entirely",
            "degradation": (
                "capability and input shape confirmed, but no okuro gate is "
                "emitted for Codex — enforcement here is instructions-only "
                "until the deny contract is observed rather than inferred. "
                "Coverage is 4 tool handlers (shell, unified_exec, "
                "apply_patch, mcp), NOT all tools — upstream issue open, so "
                "any Codex gate covers those four and nothing else"
            ),
        }

    def install_hooks(self) -> list[str]:
        """Install the UserPromptSubmit command hook + refresh its payload cache.

        Codex reads command hooks from ``~/.codex/hooks.json`` (merged with any
        inline ``[hooks]`` tables in config.toml). We write the hook script and
        register it merge-safely, preserving any user-authored hooks. The
        payload comes from the shared ``~/.okuro/profile-turn-context.txt``
        cache, refreshed here so the hook has something to inject.
        """
        generated: list[str] = []
        codex_dir = os.path.expanduser("~/.codex")
        hooks_dir = os.path.join(codex_dir, "hooks")
        try:
            os.makedirs(hooks_dir, exist_ok=True)
        except OSError as e:
            log.warning("codex: cannot create hooks dir (%s); skipping hook install", e)
            return generated

        from ._profile_compliance import atomic_write_json, write_profile_turn_context

        # 1. Hook script.
        hook_path = os.path.join(hooks_dir, self._HOOK_FILENAME)
        try:
            from ._profile_compliance import atomic_write_text
            atomic_write_text(hook_path, USER_PROMPT_HOOK)
            os.chmod(hook_path, 0o755)
            generated.append(hook_path)
        except OSError as e:
            log.warning("codex: hook script write failed: %s", e)
            return generated

        # 2. Register in hooks.json (merge-safe).
        hooks_json_path = os.path.join(codex_dir, "hooks.json")
        try:
            merged = self._merge_hooks_json(hooks_json_path, hook_path)
            atomic_write_json(hooks_json_path, merged)
            generated.append(hooks_json_path)
        except Exception as e:  # noqa: BLE001
            log.warning("codex: hooks.json merge failed: %s", e)

        # 3. Refresh the shared per-turn payload cache.
        try:
            generated.append(write_profile_turn_context())
        except Exception as e:  # noqa: BLE001
            log.warning("codex: profile-turn-context.txt refresh failed: %s", e)

        log.info(
            "codex: installed UserPromptSubmit hook %s. Trust it once via the "
            "`/hooks` command inside codex (non-managed command hooks are "
            "skipped until trusted).",
            hook_path,
        )
        return generated

    def _merge_hooks_json(self, hooks_json_path: str, hook_path: str) -> dict:
        """Return the hooks.json dict with okuro's UserPromptSubmit group merged in.

        Preserves every other event and every non-okuro handler group. Ours is
        identified by an inner handler whose ``command`` references our script
        basename, so a re-install replaces rather than duplicates it.
        """
        data: dict = {}
        if os.path.isfile(hooks_json_path):
            try:
                with open(hooks_json_path) as f:
                    loaded = json.load(f)
                if isinstance(loaded, dict):
                    data = loaded
            except (OSError, json.JSONDecodeError) as e:
                log.warning("codex: hooks.json unreadable/corrupt (%s); rewriting fresh", e)
                data = {}

        hooks_block = data.get("hooks")
        if not isinstance(hooks_block, dict):
            hooks_block = {}

        groups = hooks_block.get("UserPromptSubmit")
        if not isinstance(groups, list):
            groups = []

        basename = os.path.basename(hook_path)

        def _is_ours(group: object) -> bool:
            if not isinstance(group, dict):
                return False
            inner = group.get("hooks")
            if not isinstance(inner, list):
                return False
            for h in inner:
                if isinstance(h, dict) and basename in str(h.get("command", "")):
                    return True
            return False

        cleaned = [g for g in groups if not _is_ours(g)]
        cleaned.append({
            "hooks": [
                {
                    "type": "command",
                    "command": f'python3 "{hook_path}"',
                    "timeout": 10,
                    "statusMessage": "okuro: injecting profile context",
                }
            ],
        })

        hooks_block["UserPromptSubmit"] = cleaned
        data["hooks"] = hooks_block
        return data

    def get_subagent_protocol(self, bootstrap_context: str) -> str:
        from .template import build_subagent_protocol
        return build_subagent_protocol()
