# SPDX-License-Identifier: Apache-2.0
# <!-- AGENT_HEADER
# role: code
# purpose: Cursor provider adapter.
# index: imports | class CursorAdapter
# AGENT_HEADER_END -->
"""Cursor provider adapter.

Cursor's *global* User Rules are stored inside the app settings UI — there
is no documented file path that maps to them, so we cannot fully automate
the bootstrap directive the way we do for Claude Code or Gemini.

What we CAN do:

  - Write ``~/.cursor/rules/okuro.mdc`` as a canonical, copy-pasteable
    snippet. Some Cursor versions historically read this path (undocumented
    but observed); even where they don't, the file is the single source the
    user pastes into Settings → Rules.
  - Keep the rule body self-contained so the same text also works in a
    project-root ``AGENTS.md`` when a repo wants Cursor-native agent rules.
  - Register the okuro MCP server in ``~/.cursor/mcp.json`` — already handled
    elsewhere by ``okuro.cli.mcp_config``. The adapter itself does not write
    that file.

The adapter prints an explicit hint at install time so the manual paste
step is visible. Without it, cursor sessions reach okuro tools (MCP works)
but never call bootstrap because nothing told them to.
"""

import json
import logging
import os
import shutil

from . import register
from .base import ProviderAdapter

log = logging.getLogger(__name__)


# beforeShellExecution gate. Cursor's payload and denial shape differ from
# Claude Code's; the route matching does not, and is spliced from the shared
# contract at __MATCHER__ rather than copied.
#
# PAYLOAD (verified against cursor.com/docs/hooks.md, 2026-07-29): stdin JSON
# with the command at TOP LEVEL `command` — not `tool_input.command`, which is
# Claude Code's and Codex's shape. Also carries cwd, conversation_id,
# workspace_roots, hook_event_name, cursor_version, transcript_path.
#
# DENIAL (same source): stdout JSON
#   {"permission": "allow" | "deny" | "ask",
#    "user_message": "<shown in client>", "agent_message": "<sent to agent>"}
# Exit 2 also blocks, but the JSON contract is used because it carries a
# message TO THE AGENT — a gate that denies without naming the route is the
# failure mode that gets gates switched off.
#
# Fails open everywhere: unreadable stdin, unparseable JSON, missing command.
CURSOR_SHELL_GATE_SRC = '''#!/usr/bin/env python3
# Cursor beforeShellExecution hook: system-state reads and okuro-store reads
# route to the typed okuro tools.
# Auto-generated by okuro from data/agent_rules.yaml. Do not edit manually.
import sys, json, re, shlex, os

_ROUTES = __ROUTES__
_STORE_MARKER = __STORE_MARKER__
_STORE_CALL = __STORE_CALL__

# Operational commands that legitimately touch the store FILE rather than
# querying it for information an MCP tool serves. Mirrors the Claude emitter's
# list; denying a backup or a migration would leave the agent no route.
_OPERATIONAL = ('migrate', 'backup', '.dump', 'vacuum', 'PRAGMA integrity_check',
                'sqlite3_backup', 'cp ', 'rsync')

__MATCHER__


__CORTEX_COVERAGE__


__HUNT_DETECT__


__CORTEX_SEQUENCE__


def _allow():
    print(json.dumps({"permission": "allow"}))
    sys.exit(0)


def _session_cwd(data):
    """The directory the hunt is relative to.

    Claude Code puts it at `cwd`. Cursor's payload carries `workspace_roots`,
    and the docs do not promise `cwd` on every event -- so try both and fall
    back to the hook process's own cwd. Every path test below depends on
    getting this right, and guessing wrong only ever costs a redirect.
    """
    try:
        cwd = data.get('cwd')
        if cwd:
            return cwd
        roots = data.get('workspace_roots') or []
        if roots:
            first = roots[0]
            if isinstance(first, dict):
                first = first.get('path') or first.get('uri') or ''
            if isinstance(first, str) and first:
                return first
    except Exception:
        pass
    return os.getcwd()


def _deny(agent_message, user_message):
    print(json.dumps({
        "permission": "deny",
        "agent_message": agent_message,
        "user_message": user_message,
    }))
    sys.exit(0)


try:
    data = json.load(sys.stdin)
    command = data.get('command', '') or ''
except Exception:
    _allow()

if not command:
    _allow()

if _STORE_MARKER and _STORE_MARKER in command:
    if not any(op in command for op in _OPERATIONAL):
        # SECOND HAND-MAINTAINED COPY of the store denial. The ROUTE denial is
        # correctly shared via _gate_contract.ROUTE_DENIAL_TEMPLATE; this one
        # was left behind, which is exactly the drift that module exists to
        # prevent. Kept in sync by hand for now — folding it into the contract
        # is a separate change with its own blast radius.
        #
        # "Use the typed tool instead: <call>" became "for what you need",
        # because the route list is not always the route: this gate fired on a
        # projects-table read and named five tools, none of which lists project
        # paths (list_projects was the answer). A gate that denies without
        # naming the right route is the failure _gate_contract's own header
        # says it exists to prevent.
        _deny(
            "That reads okuro's own store directly. Use the typed tool for "
            "what you need: " + _STORE_CALL + "\\n\\n"
            "A typed tool carries the caveats a raw query drops -- window "
            "bounds, echo classification, counting notes. Operational work "
            "on the file (migrate, backup, integrity check) is not blocked.",
            "okuro: use the typed MCP tool instead of reading the store directly",
        )

hit = _match(command)
if hit:
    native, call = hit
    _deny(
        __DENIAL__.format(native=native, call=call),
        "okuro: `" + native + "` has a typed equivalent (" + call + ")",
    )

# The cortex-first rule. Last, because it is the broadest: the store and route
# checks name one resource each, this one asks a question about the whole
# command. DEFAULT IS ALLOW at every step -- _bash_hunt_target returns None for
# anything that is not a positively-identified tree hunt.
if not _cortex_already_tried():
    hunted = _bash_hunt_target(command, _session_cwd(data))
    if hunted is not None and _cortex_covers(hunted):
        _deny(
            "cortex indexes this path. That shell hunt reaches the same code "
            "via cortex_search(query, project=...) for meaning, or "
            "cortex_search_code(pattern) for an exact symbol or string -- both "
            "search the whole indexed project and return ~2 KB instead of "
            "~25 KB. Once you have asked cortex, grep is the sanctioned "
            "fallback for what it could not answer. Piping (`... | grep x`) "
            "and grep on one named file are never blocked.",
            "okuro: ask cortex first — grep stays available afterwards",
        )

_allow()
'''


def build_shell_gate_hook() -> str:
    """Render the Cursor beforeShellExecution gate from the shared contract.

    Returns "" when the contract compiles no routes at all, so a future yaml
    that drops them produces no hook rather than one that denies nothing while
    claiming coverage.
    """
    from ._gate_contract import (
        CORTEX_COVERAGE_SRC,
        CORTEX_SEQUENCE_SRC,
        HUNT_DETECT_SRC,
        ROUTE_DENIAL_TEMPLATE,
        SHELL_ROUTE_MATCHER_SRC,
        compile_store_guard,
        compile_system_state_routes,
    )

    routes = compile_system_state_routes()
    guard = compile_store_guard()
    if not routes and not guard:
        return ""
    return (
        CURSOR_SHELL_GATE_SRC
        .replace("__ROUTES__", repr(routes))
        .replace("__STORE_MARKER__", repr(guard.get("marker") if guard else ""))
        .replace("__STORE_CALL__", repr(guard.get("call") if guard else ""))
        .replace("__DENIAL__", repr(ROUTE_DENIAL_TEMPLATE))
        .replace("__MATCHER__", SHELL_ROUTE_MATCHER_SRC.strip())
        # The cortex-first rule, spliced from the SAME fragments Claude Code's
        # check-grep hook uses. Not a port and not a second implementation:
        # one definition, two payload shims.
        .replace("__CORTEX_COVERAGE__", CORTEX_COVERAGE_SRC.strip())
        .replace("__HUNT_DETECT__", HUNT_DETECT_SRC.strip())
        .replace("__CORTEX_SEQUENCE__", CORTEX_SEQUENCE_SRC.strip())
    )


_CURSOR_RULES_FRONTMATTER = """\
---
description: Okuro agent protocol — bootstrap, behavioral contract, tool routing.
alwaysApply: true
---

"""


@register
class CursorAdapter(ProviderAdapter):
    name = "cursor"

    def detect(self) -> bool:
        return (
            shutil.which("cursor") is not None
            or os.path.isdir(os.path.expanduser("~/.cursor"))
        )

    def generate_instructions(self) -> list[str]:
        from ..bootstrap.sections import build_behavioral_section
        from .template import build_instructions
        generated: list[str] = []

        rules_dir = os.path.expanduser("~/.cursor/rules")
        os.makedirs(rules_dir, exist_ok=True)

        behavioral = build_behavioral_section()
        body = build_instructions("cursor", behavioral)

        # The `.mdc` carries `alwaysApply: true`, so it is Cursor's system-tier
        # channel. Append the SAME profile-driven communication directive used
        # by the Claude output style / Codex developer_instructions / Antigravity
        # Always-On rule, so the answer-first contract lands here too and the
        # four providers never drift. Placed LAST so recency favours the closer.
        from ._profile_compliance import build_comm_directive
        directive = build_comm_directive()
        if directive and directive.strip():
            body = (
                body.rstrip()
                + "\n\n## Communication protocol (okuro)\n\n"
                + directive.strip()
                + "\n"
            )

        # Wrap in `.mdc` frontmatter so the file is a valid Cursor Project
        # Rule too — if the user copies it into a repo's `.cursor/rules/`
        # later, it'll auto-load there. The body is also AGENTS.md-compatible
        # after removing the frontmatter.
        target = os.path.join(rules_dir, "okuro.mdc")
        try:
            with open(target, "w") as f:
                f.write(_CURSOR_RULES_FRONTMATTER + body)
            generated.append(target)
        except (IOError, OSError):
            return generated

        log.info(
            "cursor: wrote %s. Cursor's *global* User Rules are UI-only — "
            "open Cursor → Settings → Rules and paste the contents of this "
            "file to enable the bootstrap directive across all sessions. "
            "(MCP server registration in ~/.cursor/mcp.json is separate and "
            "still works without this paste.)",
            target,
        )

        return generated

    def gate_bodies(self) -> dict[str, str]:
        """Cursor emits ONE gate, on `beforeShellExecution`."""
        return {"shell-gate": build_shell_gate_hook()}

    def enforcement_capability(self) -> dict:
        # CORRECTED 2026-07-29. This record used to read "ZERO enforcement of
        # native-tool routing on this provider... Cursor has no hook system",
        # with verified="install_hooks() returns [] by design". That was a
        # FALSE NEGATIVE, not a conservative one: okuro was telling the user
        # Cursor could not be enforced while Cursor shipped a GA hook system
        # with 21 events, 7 of them blocking. `install_hooks() -> []` was a
        # missing capability being reported as a design decision — the exact
        # inversion of rule 4, which exists so an absence is never silent.
        return {
            "provider": self.name,
            "blocking_pre_tool": True,
            # Cursor gates the shell through a dedicated EVENT rather than a
            # named tool, so the "tool" here is the event and the command
            # arrives at the top level of the payload — not under tool_input,
            # which is Claude Code's and Codex's shape.
            "shell_tool": "beforeShellExecution",
            "command_field": "command",
            "deny_contract": (
                '{"permission": "deny", "agent_message": ..., '
                '"user_message": ...} on stdout; exit 2 also blocks'
            ),
            "verified": "2026-07-29 — cursor.com/docs/hooks.md: 21 events, 7 "
                        "blocking (preToolUse, beforeShellExecution, "
                        "beforeMCPExecution, beforeReadFile, "
                        "beforeSubmitPrompt, subagentStart, beforeTabFileRead); "
                        "config ~/.cursor/hooks.json, project "
                        ".cursor/hooks.json, enterprise /etc/cursor/hooks.json. "
                        "Read from vendor docs, NOT observed on a live install",
            # Capability is not coverage, and documentation is not observation.
            # okuro now emits a gate here, but has never watched it fire.
            "degradation": (
                "gate is EMITTED from the shared contract but has never been "
                "observed firing on a live Cursor install — the capability and "
                "the contract come from vendor docs, not from a captured "
                "payload the way Claude Code's and Codex's did. Only "
                "beforeShellExecution is emitted; preToolUse, beforeReadFile "
                "and beforeSubmitPrompt are unused"
            ),
        }

    _HOOK_FILENAME = "okuro-shell-gate.py"

    def install_hooks(self) -> list[str]:
        """Emit the beforeShellExecution gate compiled from the tool_routing contract.

        Same spec, different emitter: the routes and the store guard come from
        ``_gate_contract`` — the same projection Claude Code's check-system and
        check-store hooks use — and only the payload/denial shape is
        Cursor-specific. Adding an action to data/agent_rules.yaml gains a
        route here on the next install, with no code change in this file.
        """
        generated: list[str] = []
        body = build_shell_gate_hook()
        if not body:
            log.warning(
                "cursor: tool_routing contract compiled no gateable routes; "
                "no hook emitted (this is a contract problem, not a Cursor one)"
            )
            return generated

        cursor_dir = os.path.expanduser("~/.cursor")
        hooks_dir = os.path.join(cursor_dir, "hooks")
        try:
            os.makedirs(hooks_dir, exist_ok=True)
        except OSError as e:
            log.warning("cursor: cannot create hooks dir (%s); skipping", e)
            return generated

        from ._profile_compliance import atomic_write_json, atomic_write_text

        hook_path = os.path.join(hooks_dir, self._HOOK_FILENAME)
        try:
            atomic_write_text(hook_path, body)
            os.chmod(hook_path, 0o755)
            generated.append(hook_path)
        except OSError as e:
            log.warning("cursor: hook script write failed: %s", e)
            return generated

        hooks_json_path = os.path.join(cursor_dir, "hooks.json")
        try:
            atomic_write_json(
                hooks_json_path, self._merge_hooks_json(hooks_json_path, hook_path)
            )
            generated.append(hooks_json_path)
        except Exception as e:  # noqa: BLE001
            log.warning("cursor: hooks.json merge failed: %s", e)

        log.info("cursor: installed beforeShellExecution gate %s", hook_path)
        return generated

    def _merge_hooks_json(self, hooks_json_path: str, hook_path: str) -> dict:
        """Return hooks.json with okuro's beforeShellExecution entry merged in.

        Preserves every other event and every non-okuro entry. Ours is
        identified by our script basename in its ``command``, so a re-install
        replaces rather than duplicates.
        """
        data: dict = {}
        if os.path.isfile(hooks_json_path):
            try:
                with open(hooks_json_path) as f:
                    loaded = json.load(f)
                if isinstance(loaded, dict):
                    data = loaded
            except (OSError, json.JSONDecodeError) as e:
                log.warning(
                    "cursor: hooks.json unreadable/corrupt (%s); rewriting fresh", e
                )
                data = {}

        data["version"] = 1
        hooks_block = data.get("hooks")
        if not isinstance(hooks_block, dict):
            hooks_block = {}

        entries = hooks_block.get("beforeShellExecution")
        if not isinstance(entries, list):
            entries = []

        basename = os.path.basename(hook_path)
        cleaned = [
            e for e in entries
            if not (isinstance(e, dict) and basename in str(e.get("command", "")))
        ]
        cleaned.append({
            "type": "command",
            "command": f'python3 "{hook_path}"',
            "timeout": 10,
            # FAIL OPEN. A crashed gate must not stop the user working — the
            # same reasoning that keeps every okuro hook's except-branch on
            # exit 0. A gate that blocks when it breaks is one people delete,
            # and they take the routes that did work with them.
            "failClosed": False,
        })

        hooks_block["beforeShellExecution"] = cleaned
        data["hooks"] = hooks_block
        return data

    def get_subagent_protocol(self, bootstrap_context: str) -> str:
        from .template import build_subagent_protocol
        return build_subagent_protocol()
