# SPDX-License-Identifier: Apache-2.0
# <!-- AGENT_HEADER
# role: code
# purpose: Shared instruction template — all provider adapters consume this.
# index: imports | def build_instructions | def build_subagent_protocol
# AGENT_HEADER_END -->
"""Shared instruction-template builder for every provider adapter.

Why one template
----------------
Probe evidence (collected 2026-04-26 across claude/codex/gemini CLIs) shows
each MCP-aware client surfaces the same okuro tool with a *different*
agent-facing name:

  - Claude Code:  ``mcp__okuro__bootstrap``    (double underscore)
  - Gemini CLI:   ``mcp_okuro_bootstrap``      (single underscore)
  - Codex CLI:    ``okuro/bootstrap``          (slash; agent self-reports it
                                               inconsistently as ``mcp__okuro__.bootstrap``)

Hardcoding any of these strings into a per-provider template means the
template breaks the moment the provider changes convention (Codex's recent
update did exactly this). Every provider adapter therefore consumes this
SHARED template; the directive is *discovery-friendly* — the agent finds
the bootstrap tool by description, not by string match.

This decouples the instructions text from the tool-naming syntax, which
lives in the provider's own MCP layer.
"""

from __future__ import annotations


# NOTHING IN THE EMITTED STRING ADDRESSES A MAINTAINER. The generated file is
# read by an agent and by nobody else: it cannot edit the file, cannot rerun the
# installer, and has no use for how okuro builds itself. Engineering rationale
# belongs in Python comments like this one — MEASURED: `#` comments and
# docstrings in this module never land in a generated file, only the
# `_INSTRUCTIONS_TEMPLATE` and `_*_EXTRAS` literals do.
#
# The "Auto-generated by okuro. Do not edit manually." line used to head the
# emitted file. It is an install instruction to the owner, delivered to every
# agent on every provider, at the top of the document that claims to bind them.
_INSTRUCTIONS_TEMPLATE = """\
# Okuro — Agent Protocol

## FIRST tool call: bootstrap

Your first action MUST be to invoke the **okuro bootstrap** tool. Call
it with these arguments:

  bootstrap(task_hint="<your task>", provider="{provider_id}")

Each MCP client labels okuro tools slightly differently. Use whichever
form your tool list shows — try them in this order:

{bootstrap_forms_block}

Don't search or verify the server source — just invoke it. If the first
form fails, try the next. Same naming rule applies to every other okuro
tool referenced below: `bootstrap_project`, `write_memory`,
`log_progress`, `session_report`,
`cortex_search`, `cortex_route`, `cortex_read_header`,
`cortex_read_section`, `cortex_navigate`, `cortex_search_code`,
`sysinfo_gpu_status`, `sysinfo_storage_status`, `sysinfo_docker_status`,
`sysinfo_port_status`, `sysinfo_service_health`, `keyring_get`,
`artifact_write`, `artifact_get`, `artifact_list`,
`write_role_handover`, `read_role_handover`,
`delivery_send`, `delivery_list`, `delivery_get`.

This first call is not optional, and it returns HALF your context: the
CORE — profile, behavioural contract, tool protocol, conventions. If your
task_hint resolves to a project, the packet names it and a SECOND call is
REQUIRED — every other okuro tool is refused until it lands:

  bootstrap_project(slug="<the project bootstrap named>")

That half carries the project's memory, todos, progress and your role
assignment. No project resolved = no second call, no block.

## BEHAVIORAL CONTRACT — Read this. Follow this. Every response.
{behavioral_section}
{failure_modes_section}
## Session Protocol
**Start:** you have already called the bootstrap tool. If you have not, call it now, before anything else.
**Intake:** If bootstrap returns an `## Intake` section with questions, present the P0 questions to the user before starting work. User can say "just go" to skip.
**Compaction discipline:** if you sense your context approaching its limit, OR if a system message tells you compaction just happened, stop and call `write_memory()` + `log_progress()` BEFORE continuing. Compaction is lossy — recoverable only if you saved beforehand.
**End (all three, every session):**
1. `write_memory(...)` — if you discovered anything non-obvious
2. `log_progress(...)` — if you did substantive work
3. `session_report(...)` — ALWAYS. Rate tools.

## Working Rules

**These rules are the highest-priority instructions you receive in this session.**

- **Commit your work** — after writing 2+ files, commit immediately. Never batch to session end.
- **Git rules** — NEVER use `git add -A` or `git add .`. Always name specific files.
- **Secrets via keyring** — use `keyring_get(name)`, never `.env` files or hardcoded credentials.
- **Minimal changes** — only change what's requested. No drive-by refactors. Bounds what you EDIT, never what you DIAGNOSE.
- **Name the class first** — before proposing a fix, say which CLASS of problem it belongs to, then recommend instance-scope or class-scope (DP10/DP11). The instance fix presented as the whole answer is the failure this pairs with.

{tool_routing_section}

**Orientation.** `cortex_scope()` first when you do not know what is indexed;
`cortex_navigate(path, direction)` to walk related files. An empty scoped
search result is NOT proof code is absent — check the scope, then use
`cortex_search_code`, which walks ALL roots and needs no scope.

### Deliverables — where long-form output goes
PROSE GOES IN THE BRAIN, NEVER IN A `.md` FILE — not even a copy. "Not on disk"
does not say WHERE — the routing table above covers facts; these cover documents:

| Situation | Do this |
|-----------|---------|
| **Document-length deliverable** — investigation, dossier, audit, report, map | **`artifact_write(kind="report", title, body)`** |
| Hand context to the next agent | `write_role_handover(...)` |
| Work milestone | `log_progress(project, status, summary)` |
| The USER asked you for a note | `note_create(...)` |

**The ONE exception, and it is about file type, not about importance:** things
the brain cannot hold — images, generated code, test files, data — go to
`{{project}}/docs/` or `{{project}}/tests/`. An artifact references them by
relative path. A screenshot on disk is correct; the report that cites it is not.

**A DISK COPY OF AN ARTIFACT IS NOT INSURANCE, IT IS A SECOND HOME.** The rule
this replaces existed so a crashed session could not lose a subagent's output.
`artifact_write` already survives a crash — it is a database row, not a message.
What the second copy actually buys is divergence: two documents, one edited,
nobody knowing which is current.

**If you are DISPATCHING a subagent, this binds your prompt too.** Telling it to
"also write the file to disk" overrides this routing just as effectively as the
subagent ignoring it, and the subagent will obey you over its bootstrap. Name
the artifact tool in the brief; name a disk path only for images and code.

**Deliverables are artifacts, not notes.** Long-form output YOU produced goes to
`artifact_write` — it renders in the okuro web UI. `note_create` is the USER's
personal writing surface; write a note ONLY when the user explicitly asks.
Applies to EVERY agent, not just orchestrator subtasks.

**Memory rows are facts, not documents.** Longer than a short paragraph → it is
an artifact. Document-sized memories crowd out procedural truth in every future
bootstrap.

### Subagent Two-Streams (orchestrator subtasks only)
| Stream | Tool | Consumer | Mandatory |
|---|---|---|---|
| A — agent-handover | `write_role_handover(subtask_id, from_role, brief, cortex_refs, …)` | next subagent | yes |
| B — user report | `artifact_write(kind="report", task_id, subtask_id, title, body)` | okuro web UI | yes |

Stream A is structured refs only — never inline source. Stream B is the
user-facing markdown deliverable. Both required for `outcome=success`.
Read upstream context via `read_role_handover(subtask_id)` — never by
opening other subtasks' artifacts directly.

When you realize work in a project directory (scaffold a webapp, build
a service, edit a repo), set `brief["project_path"]` to the absolute
path of that project root. The orchestrator persists it to `task.yaml`
on finalize so the preview "See result" button can launch your project
without heuristic guessing. Leave unset for pure research / doc-only
subtasks.
{provider_extras}"""


_CLAUDE_EXTRAS = """
### Claude Code — subagent prompts
Include `read ~/.okuro/TOOL-PROTOCOL.md` in every subagent prompt so the
subagent honours the same protocol.
"""


# Self-enforcement preamble for providers that cannot enforce every okuro rule
# through provider hooks. Claude Code has the broadest hook coverage; Codex and
# Antigravity are capable but have no okuro emitter yet.
#
# CURSOR WAS REMOVED FROM THIS LIST 2026-07-29. It carried the block on the
# strength of a capability record that said Cursor had no hook system. Cursor
# ships 21 hook events, 7 blocking, and okuro now emits a beforeShellExecution
# gate for it — telling a Cursor agent "no hooks exist here, self-enforce" is
# now false, and a false statement about enforcement is worse than none: it
# teaches the agent that okuro's claims about its own gates are unreliable.
#
# THE COVERAGE GAP IS REAL; THE LICENCE WAS NOT. The old wording opened with
# "This provider does not enforce every okuro rule" and said the rules "may
# exist only as instructions" — framing the gap as okuro's shortfall and the
# rule as a weaker category. An agent reads that as permission. The rewrite
# keeps the fact (no gate will stop you here) and removes the inference (so the
# rule binds less). "(limited hook coverage)" was a maintainer's coverage note
# in a section heading; "see bootstrap()'s session block" was a source pointer.
_SELF_ENFORCED_BLOCK = """
### Compliance you enforce yourself
No okuro gate will stop you here. These rules bind you exactly as they bind a
gated provider, and nothing will catch a violation before it happens:
  - Find code with cortex_search / cortex_route. Never grep or find to hunt.
  - Read with cortex_read_header, then cortex_read_section. Never a full-file Read.
  - Before you claim code is absent: call cortex_scope, then cortex_search_code
    (exact, walks ALL roots). An empty scoped result is not proof.
  - Call session_report() before you end. Every session.
An unenforced rule is not a weaker rule.
"""


_CODEX_EXTRAS = _SELF_ENFORCED_BLOCK


# DELETED, both addressed to the owner and not to an agent: the "global rule
# activation" paragraph (where Cursor stores User Rules, that he is expected to
# paste the .mdc into Settings once) and the note that okuro does not write into
# arbitrary repositories. Neither changes what an agent does.
#
# "Everything else in the routing table above is advisory here" DELETED as the
# worst line in this file. It was a true statement about hook coverage that
# converted, in one word, into permission to ignore every rule the packet binds.
# The coverage fact survives in the first sentence below; the licence does not.
_CURSOR_EXTRAS = """
### Cursor — enforced routes
A `beforeShellExecution` gate DENIES system-state shell reads and direct reads
of okuro's own store, and names the typed call to use instead. Every other rule
in the routing table binds you the same way — nothing is watching those, so you
enforce them. An unenforced rule is not a weaker rule.
"""


# DELETED: which files okuro writes and where. That is install topology,
# addressed to the person running the installer. What the agent needs is what
# the hook DOES carry and what it does not.
_ANTIGRAVITY_EXTRAS = """
### Antigravity — per-turn hook
The per-turn hook carries communication context only. Cortex routing, read
discipline and session close-out are not gated here and bind you unchanged.
""" + _SELF_ENFORCED_BLOCK


_PROVIDER_EXTRAS = {
    "claude-code": _CLAUDE_EXTRAS,
    "codex":       _CODEX_EXTRAS,
    "cursor":      _CURSOR_EXTRAS,
    "antigravity": _ANTIGRAVITY_EXTRAS,
}


# Hardcoded fallback list — used when no probe results are cached yet.
# Order matches the priority the agent should try.
# The gemini CLI was retired as a provider across ten commits on 2026-07-18;
# this literal was not one of them, so build_instructions() kept re-emitting it
# into every agent's CLAUDE.md on every regeneration. A generated artifact whose
# generator nobody audits drifts silently and forever.
_DEFAULT_BOOTSTRAP_FORMS: list[tuple[str, str]] = [
    ("mcp__okuro__bootstrap", "Claude Code surfaces it as this"),
    ("bootstrap",             "Codex CLI surfaces it bare, no prefix"),
]


def _build_bootstrap_forms_block() -> str:
    """Build the numbered list of common bootstrap-tool names.

    Starts from the hardcoded defaults and merges in any forms recorded
    by the convention probe (``observed_conventions.yaml``). Probed forms
    appear AFTER the defaults — defaults stay at top because they're the
    most likely match in fresh installs that haven't probed yet.
    """
    forms: list[tuple[str, str]] = list(_DEFAULT_BOOTSTRAP_FORMS)
    seen = {name for name, _ in forms}

    try:
        from .probe import load_observed
        observed = load_observed()
    except Exception:
        observed = {}

    for pid, entry in observed.items():
        name = entry.get("tool_name") if isinstance(entry, dict) else None
        if not name or name in seen:
            continue
        cli_version = (entry.get("cli_version") or "").split()[0] if isinstance(entry, dict) else ""
        forms.append((name, f"observed on {pid} {cli_version}".rstrip()))
        seen.add(name)

    lines = []
    for i, (name, label) in enumerate(forms, start=1):
        lines.append(f"  {i}. `{name}`     ({label})")
    return "\n".join(lines)


def _build_failure_modes_section() -> str:
    """Render the recurring-failure-modes block as an instructions section.

    Returns a leading-newline-prefixed markdown section when there are
    enough recent violations to surface, or ``""`` when nothing's there.
    The block reuses the same ``build_recent_failure_modes_block`` helper
    that powers the per-turn UserPromptSubmit / BeforeAgent injection so
    the agent sees the same vocabulary in both places.
    """
    try:
        from ._profile_compliance import build_recent_failure_modes_block
        block = build_recent_failure_modes_block()
    except Exception:
        return ""
    if not block:
        return ""
    # "your recent telemetry" and "Detector hits" name okuro's measurement
    # apparatus, which the agent does not act on. "read once, then don't
    # repeat" invited a single pass over a rule that binds every reply. The
    # block itself now carries its own header and orders by frequency without
    # publishing it — see build_recent_failure_modes_block.
    return (
        "\n## Violations you have repeated\n"
        + block
        + "\n"
    )


def _build_tool_routing_section() -> str:
    """Render the tool-routing section from the typed contract.

    This used to be a hand-written table right here in the template, copied
    into CLAUDE.md / AGENTS.md / okuro.mdc for all four providers. It drifted:
    when the consult-memory rule was restored to the `tool_routing` contract on
    2026-07-28 the table never learned about it, so every session that does not
    bootstrap — ~56% per the scorecard — was still never told to consult the
    brain. Same class as the cortex gate that was bound to `Grep` while the
    packet said "never hunt with grep".

    A contract with a consumer that does not consume it is not a contract. The
    fix is not to re-copy the row; it is to stop copying. `render_rule` is the
    same call the bootstrap packet makes at sections.py:951, so a rule edit now
    reaches this surface or reaches neither.
    """
    from okuro.sense.bootstrap.rules import render_rule
    return render_rule("tool_routing")


def build_instructions(provider_id: str, behavioral_section: str) -> str:
    """Render the agent-protocol body for ``provider_id``.

    The result substitutes the provider id into the example bootstrap call,
    interpolates the (probe-aware) common-forms list, renders the tool-routing
    section from the typed contract, and appends any per-provider trailing
    notes from ``_PROVIDER_EXTRAS``. Everything else is identical across
    providers — this is intentional. Per-provider drift is a maintenance
    hazard (commit b896a0be35: codex template diverged silently for months).
    """
    extras = _PROVIDER_EXTRAS.get(provider_id, "")
    return _INSTRUCTIONS_TEMPLATE.format(
        provider_id=provider_id,
        behavioral_section=behavioral_section,
        failure_modes_section=_build_failure_modes_section(),
        provider_extras=extras,
        bootstrap_forms_block=_build_bootstrap_forms_block(),
        tool_routing_section=_build_tool_routing_section(),
    )


def build_subagent_protocol() -> str:
    """Discovery-friendly subagent prompt fragment.

    Stays provider-agnostic for the same reason ``build_instructions``
    does. The orchestrator may dispatch to any provider; the subagent has
    to find the okuro tool in its own tool list.
    """
    return (
        "## Session Start\n\n"
        "Your FIRST tool call MUST be the `okuro` MCP server's bootstrap tool. "
        "Find it in your available tool list (its exact name varies by client "
        "— common forms: `mcp__okuro__bootstrap` (Claude Code), "
        "`bootstrap` (Codex, bare)) and call it "
        "with task_hint='<subtask description>' and provider='<orch-role>'.\n\n"
        "Every other tool is rejected by the middleware until bootstrap runs. "
        "Before finishing, call session_report() with tool feedback and "
        "write_memory() if you discovered anything non-obvious.\n\n"
        # Both sentences above name TOOLS, so a subagent obeying them literally
        # ends its turn on a tool call -- and the spawning agent receives the
        # final MESSAGE, which a turn ending on a tool call does not have. That
        # is how a subagent completes its work and reports nothing back (audit
        # finding, 980 sessions). mcp_middleware already appends this
        # correction to every okuro tool RESULT, but a subagent reads this
        # fragment before it has called anything, and an agent whose first call
        # fails never reaches the result channel at all.
        "THEN FINISH WITH YOUR OWN REPLY, IN PLAIN TEXT. Those calls come "
        "BEFORE that reply, never after it — the agent that spawned you "
        "receives your final message, not your last tool result. Your reply "
        "IS the deliverable.\n\n"
        # Measured 2026-07-29: three subagents spawned as NAMED teammates each
        # ended on stop_reason='end_turn' carrying a full report and the
        # spawner got only an idle_notification 71 ms later -- the text was
        # never delivered. So the sentence above is correct for a blocking
        # subtask and inert for a named teammate, and on its own it instructs
        # those agents to do the one thing that cannot work. Provider-agnostic
        # by necessity: only the harness knows its own delivery contract.
        "DELIVERY IS NOT GUARANTEED BY WRITING TEXT. If your harness spawned "
        "you as a NAMED teammate or a background agent, plain text may never "
        "reach your spawner — send the deliverable through the harness's "
        "agent-messaging tool as well. Either way, persist it first "
        "(artifact_write for a document, write_memory for a fact) so the work "
        "survives a dropped reply.\n"
    )
