// <!-- AGENT_HEADER
// role: code
// purpose: okuro·prism multimodal blocks — media generated by okuro's LOCAL
//   models embedded in a deck. AudioBrief: a spoken briefing (on-box TTS) as a
//   self-contained data-URI <audio> player + collapsible transcript.
// index: fmtDur | AudioBrief
// AGENT_HEADER_END -->
import type { Block } from "@/lib/prism-api";

type AudioData = Extract<Block, { type: "audiobrief" }>;

/** Seconds → "1:05" / "0:42". */
function fmtDur(s: number): string {
  const m = Math.floor(s / 60);
  const r = Math.round(s % 60);
  return `${m}:${String(r).padStart(2, "0")}`;
}

/** AUDIO BRIEF — a facet's takeaway spoken by an on-box TTS voice. `data.src`
 *  is usually a self-contained data-URI (survives export, no serving route),
 *  but any playable URL works — the pulse sidepanel's brief indicator feeds
 *  it a tokenised `/api/assets/media/{id}/file` URL instead. `preload="none"`
 *  keeps the (possibly ~1 MB) clip off the critical path until played. */
export function AudioBrief({
  data,
  accent,
  onPlay,
}: {
  data: AudioData;
  accent: string;
  /** Fires on the native `play` event — callers use this as the "heard" signal. */
  onPlay?: () => void;
}) {
  if (!data.src) return null;
  return (
    <figure className="rounded-lg border border-current/10 p-3">
      <figcaption className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide opacity-70">
        <span aria-hidden>🎧</span> Audio brief
        {typeof data.duration === "number" && (
          <span className="ml-auto font-normal tabular-nums opacity-55">{fmtDur(data.duration)}</span>
        )}
        {data.voice && <span className="font-normal normal-case opacity-45">· {data.voice}</span>}
      </figcaption>
      <audio controls preload="none" src={data.src} onPlay={onPlay} className="w-full" style={{ accentColor: accent }} />
      {data.transcript && (
        <details className="mt-2 text-xs opacity-70">
          <summary className="cursor-pointer select-none opacity-80">transcript</summary>
          <p className="mt-1 leading-relaxed">{data.transcript}</p>
        </details>
      )}
      {data.caption && <p className="mt-2 text-xs opacity-60">{data.caption}</p>}
    </figure>
  );
}
