# SPDX-License-Identifier: Apache-2.0
# <!-- AGENT_HEADER
# role: code
# purpose: the synthetic append-only release commit. Never pushes.
# index:
#   imports
#   class PublishError
#   def _git
#   def release_commit
# AGENT_HEADER_END -->
"""One synthetic commit per release, parent = previous release commit.

install/update on every stakeholder machine is ``git clone`` + ``git pull
--ff-only`` (scripts/update.sh) — so release history is APPEND-ONLY and
NEVER re-rooted; a re-squash bricks every install at once. This module
asserts that property instead of trusting itself.

There is deliberately no push here. A release push is a human act:
push-audit protocol first, then the owner's explicit in-the-moment word.
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path


class PublishError(RuntimeError):
    """A release-commit invariant failed — the release repo is untouched
    or the offending commit was not created."""


def _git(repo: Path, *args: str, check: bool = True) -> str:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True, text=True, errors="replace",
    )
    if check and proc.returncode != 0:
        raise PublishError(f"git {' '.join(args)}: {proc.stderr.strip()}")
    return proc.stdout


def _rev(repo: Path, ref: str) -> str | None:
    proc = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--verify", "--quiet", ref],
        capture_output=True, text=True,
    )
    return proc.stdout.strip() or None


def release_commit(
    export_dir: Path,
    release_repo: Path,
    *,
    source_sha: str,
    version: str,
) -> str:
    """Replace the release worktree with the export and commit it.

    Returns the new commit sha. Invariants asserted, not assumed:
    the repo is clean before we start; the new commit's parent IS the
    previous tip; the root commit is unchanged when history exists.
    """
    export_dir, release_repo = Path(export_dir), Path(release_repo)
    if not (release_repo / ".git").exists():
        raise PublishError(f"{release_repo} is not a git repository")
    if _git(release_repo, "status", "--porcelain").strip():
        raise PublishError(f"release repo {release_repo} has uncommitted changes")

    prev_tip = _rev(release_repo, "HEAD")
    prev_root = (
        _git(release_repo, "rev-list", "--max-parents=0", "HEAD").strip()
        if prev_tip else None
    )

    # Empty the worktree (everything but .git), then copy the export in.
    for entry in release_repo.iterdir():
        if entry.name == ".git":
            continue
        subprocess.run(["rm", "-rf", str(entry)], check=True)
    subprocess.run(
        ["cp", "-a", *[str(p) for p in export_dir.iterdir()], str(release_repo)],
        check=True,
    )

    # Stage by explicit pathspec list — deterministic, and honest about
    # what a generated tree is: the file list IS the change. The union with
    # the previously tracked list is what stages DELETIONS (a file the last
    # release shipped and this one does not).
    previously_tracked = {
        p for p in _git(release_repo, "ls-files", "-z").split("\0") if p
    }
    current = {
        rel
        for p in release_repo.rglob("*")
        if p.is_file()
        for rel in [str(p.relative_to(release_repo))]
        if rel.split("/", 1)[0] != ".git"
    }
    with tempfile.NamedTemporaryFile("w", suffix=".paths", delete=False) as fh:
        fh.write("\n".join(sorted(previously_tracked | current)) + "\n")
        pathspec_file = fh.name
    _git(release_repo, "add", f"--pathspec-from-file={pathspec_file}")

    message = (
        f"release: okuro {version}\n\n"
        f"Generated by the release-by-export pipeline.\n"
        f"Source-sha: {source_sha}\n"
    )
    _git(release_repo, "commit", "--allow-empty", "-m", message)
    new_tip = _rev(release_repo, "HEAD")
    if new_tip is None:
        raise PublishError("commit did not produce a HEAD")

    # Append-only parentage, asserted from the repo itself.
    parents = _git(release_repo, "rev-list", "--parents", "-n", "1", new_tip).split()
    actual_parents = parents[1:]
    if prev_tip is None:
        if actual_parents:
            raise PublishError("first release commit unexpectedly has a parent")
    else:
        if actual_parents != [prev_tip]:
            _git(release_repo, "reset", "--hard", prev_tip)
            raise PublishError(
                f"parentage violated: expected [{prev_tip[:12]}], "
                f"got {[p[:12] for p in actual_parents]} — reset to previous tip"
            )
        new_root = _git(release_repo, "rev-list", "--max-parents=0", "HEAD").strip()
        if new_root != prev_root:
            _git(release_repo, "reset", "--hard", prev_tip)
            raise PublishError("history was re-rooted — reset to previous tip")

    return new_tip
