#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Emit board/theme.css from A1's resolved-theme fixture JSONs.

Each fixture is A1 theme-resolver output: a flat {"tokens": {"--x": "..."}}
dict validated against token_manifest("board") (62 tokens), plus brand_id /
mode / warnings. This wraps every fixture in a :root[data-theme="<slug>"]
block so a single gallery page can switch brands with a data-theme attribute
(and the playwright harness can pin one via ?theme=<slug>). The slug is the
STABLE filename key, not brand_id — brand_id is the human label. The FIRST
fixture also emits a bare :root default.

DERIVED TOKENS (this file, not A1's manifest): the kit's components consume a
few convenience tokens the 62-token manifest does not ship. Rather than
hand-hardcode them, we DERIVE them per-brand from existing manifest tokens so
they track any brand:
  --accent-ink   text-on-accent: dark ink on a light accent, light ink on a
                 dark accent (relative luminance of --accent, threshold 0.5)
  --ok-dim       --ok at 12% alpha (matches A1's --warn-dim / --info-dim rule)
  --persona-a/-b/-c  categorical persona marks, aliased to --info / --gold /
                 --violet (semantic tokens already in the manifest)
Rerun whenever A1 ships new fixtures:  python fixtures/gen_theme_css.py
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "board" / "theme.css"

# (filename, stable data-theme slug) — order matters: first = default :root
# Three correctly-attributed stored brands (A1b brand schema v2).
FIXTURES = [
    ("theme-okuro.json", "okuro"),        # dark · JetBrains Mono · green
]


def _hex_to_rgb(v: str):
    m = re.match(r"#([0-9a-fA-F]{6})$", v.strip())
    if not m:
        return None
    h = m.group(1)
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def derive_tokens(tokens: dict) -> dict:
    """Convenience tokens NOT in the manifest, derived from it. NB --accent-ink
    and --accent-text are now RESOLVER-owned (manifest v2) — do not derive them
    here; only --ok-dim and the persona aliases remain gaps."""
    out: dict[str, str] = {}
    ok = _hex_to_rgb(tokens.get("--ok", ""))
    if ok:
        out["--ok-dim"] = f"rgba({ok[0]}, {ok[1]}, {ok[2]}, 0.12)"
    # categorical persona marks -> existing semantic tokens
    out["--persona-a"] = "var(--info)"
    out["--persona-b"] = "var(--gold)"
    out["--persona-c"] = "var(--violet)"
    return out


def block(selector: str, tokens: dict, derived: dict) -> str:
    lines = [f"{selector} {{"]
    for k, v in tokens.items():
        lines.append(f"  {k}: {v};")
    if derived:
        lines.append("  /* derived (not in board manifest) — see gen_theme_css.py */")
        for k, v in derived.items():
            lines.append(f"  {k}: {v};")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    parts = [
        "/* GENERATED by fixtures/gen_theme_css.py from A1 theme-resolver output. Do not edit by hand. */",
        "/* Brand-resolved tokens (62-token board manifest) + a few DERIVED convenience tokens. */",
        "/* Structural extras (canvas, ultra-w, line-heights, weights) live in board/tokens.css. */",
        "",
    ]
    for i, (name, slug) in enumerate(FIXTURES):
        path = HERE / name
        if not path.exists():
            continue
        data = json.loads(path.read_text())
        brand = data.get("brand_id", slug)
        mode = data.get("mode", "")
        tokens = data["tokens"]
        derived = derive_tokens(tokens)
        warnings = data.get("warnings") or []
        note = data.get("note") or (warnings[0] if warnings else "")
        parts.append(f"/* {slug} — brand={brand} · mode={mode}" + (f" · {note}" if note else "") + " */")
        if i == 0:
            parts.append(block(":root", tokens, derived))
            parts.append("")
        parts.append(block(f':root[data-theme=\"{slug}\"]', tokens, derived))
        parts.append("")
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
